site_name: Сайт и блог Бориса Романова

theme:
    name: material
    palette:
        scheme: slate
        primary: amber
        accent: purple

plugins:
  - search
  - callouts
  - tags:
      tags_file: tags.md


markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences