site_name: Сайт и блог Бориса Романова
copyright: Copyright &copy; 2022 Boris Romanov

theme:
    name: material
    language: ru
    palette:
        scheme: slate
        primary: amber
        accent: purple
    custom_dir: overrides


plugins:
  - search:
        lang: ru
  - callouts
  - tags:
      tags_file: tags.md
  - exclude:
      glob:
        - draft/*

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences