site_name: Сайт и блог Бориса Романова

theme:
    name: material
    language: ru
    palette:
        scheme: slate
        primary: amber
        accent: purple


plugins:
  - search:
        lang: ru
  - callouts
  - tags:
      tags_file: tags.md


markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences